##
# 	Bitburner server
#
# @file
# @version 0.1

run:
	docker run -it --rm -p 8080:80 --name web -v ~/git/bitburner/html:/usr/share/nginx/html -v ~/git/bitburner/server/configs:/etc/nginx/conf.d nginx
# end
